### ISSUE TITLE
Currency seperator handling

### ISSUE THREAD

**Issue by CodeDotJS** [reworkd/harambe#52]
In [`type_currency.py`](https://github.com/reworkd/harambe/blob/main/harambe/parser/type_currency.py) the logic for distinguishing between thousands separators and decimal points seems error prone. For instance, it assumes that periods `(.)` are always thousands separators when they may actually represent decimal points, which could lead to incorrect parsing of formats like `"$1,234,56.78"`. 

https://github.com/reworkd/harambe/blob/b9fa82b4655c9c80b63d4224f7d4ceadebe980eb/harambe/parser/type_currency.py#L20-L23

Also, which locale is being used for currency parsing in the current implementation?

**Comment by mohamedmamdouh22** [comment]
the case you mentioned will succeed and be parsed to `123456.78`, we just need to separate between European format and American format, it will only fail in case 3 decimal numbers after the decimal point cuz in this case it is hard to know if this is thousand operator ore decimal separator like 1.234$ and 1.234€
and yeah this is the current currency parser
